# Generated by Django 3.2 on 2021-04-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20210428_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityweather',
            name='dew_point',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cityweather',
            name='feels',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cityweather',
            name='pressure',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cityweather',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cityweather',
            name='uvi',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cityweather',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
